### ISSUE TITLE
随便玩了下就崩溃了.

### ISSUE THREAD

**Issue by renqingyou** [18Gray/ProCamera#20]

**Comment by renqingyou** [comment]
08-31 16:10:36.532 5122-5226/com.eighteengray.procamera E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                          Process: com.eighteengray.procamera, PID: 5122
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.setRepeatingRequest(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
                                                                              at com.eighteengray.procameralibrary.camera.BaseCamera2TextureView.updatePreview(BaseCamera2TextureView.java:282)
                                                                              at com.eighteengray.procameralibrary.camera.Camera2TextureView$2.onConfigured(Camera2TextureView.java:340)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                              at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                              at android.os.Handler.handleCallback(Handler.java:815)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                              at android.os.Looper.loop(Looper.java:207)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by 18Gray** [comment]
非常感谢，因为我手头就俩手机，有些问题可能在我这暴露不出来，感谢支持。
