### ISSUE TITLE
Unable to open trace file '/sdcard/ProCamera.trace': Permission denied

### ISSUE THREAD

**Issue by xhAndroid** [18Gray/ProCamera#26]
05-16 09:46:52.906 20661-20661/com.eighteengray.procamera E/art: Unable to open trace file '/sdcard/ProCamera.trace': Permission denied
05-16 09:46:52.910 20661-20661/com.eighteengray.procamera E/CrashHandler: dump crash info failed
05-16 09:46:52.912 20661-20661/com.eighteengray.procamera E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.eighteengray.procamera, PID: 20661
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eighteengray.procamera/com.eighteengray.procamera.MainActivity}: java.lang.RuntimeException: Unable to open trace file '/sdcard/ProCamera.trace'
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
                                                                                at android.app.ActivityThread.access$1100(ActivityThread.java:156)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:157)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
                                                                             Caused by: java.lang.RuntimeException: Unable to open trace file '/sdcard/ProCamera.trace'
                                                                                at dalvik.system.VMDebug.startMethodTracingFilename(Native Method)
                                                                                at dalvik.system.VMDebug.startMethodTracing(VMDebug.java:167)
                                                                                at android.os.Debug.startMethodTracing(Debug.java:963)
                                                                                at android.os.Debug.startMethodTracing(Debug.java:916)
                                                                                at com.eighteengray.procamera.MainActivity.onCreate(MainActivity.java:31)
                                                                                at android.app.Activity.performCreate(Activity.java:6362)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
                                                                                at android.app.ActivityThread.access$1100(ActivityThread.java:156) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:157) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by 18Gray** [comment]
Permission denied，是不是权限检查的时候没有同意SD卡的权限？

**Comment by AccountZk** [comment]
大概说一下碰到的问题，应用安装之后无法启动。检测日志，在MainActivity中注释掉 Debug.startMethodTracing("ProCamera"); 可解决无法启动的问题。

启动之后碰到的问题: 
1: BaseActivity中requestWindowFeature(Window.FEATURE_NO_TITLE);导致崩溃
2.指向BaseActivity中initCommonTitle(); 具体日志如下:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eighteengray.procamera/com.eighteengray.procamera.imageprocess.activity.ImageProcessActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.eighteengray.procamera.activity.BaseActivity.initCommonTitle(BaseActivity.java:117)
        at com.eighteengray.procamera.activity.BaseActivity.onCreate(BaseActivity.java:43)
        at com.eighteengray.procamera.imageprocess.activity.ImageProcessActivity.onCreate(ImageProcessActivity.java:21)

3.打开图库,指向(ImageProcessActivity.java:24); 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eighteengray.procamera/com.eighteengray.procamera.imageprocess.activity.ImageProcessActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.eighteengray.procamera.imageprocess.activity.ImageProcessActivity and its super classes have no public methods with the @Subscribe annotation

以上问题，运行在华为7i这款比较奇葩的手机上。

**Comment by AccountZk** [comment]
补充

 运行环境的NDK版本:  15.1.4119039 
是不是需要更换到16.x

**Comment by 18Gray** [comment]
先更新下代码看看，我最近提了比较多代码。
