### ISSUE TITLE
小米5s  点击拍照的时候报错

### ISSUE THREAD

**Issue by zjianflys** [18Gray/ProCamera#29]
`06-21 10:45:08.848 25695-28453/com.eighteengray.procamera E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                            Process: com.eighteengray.procamera, PID: 25695
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                                at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.checkState(Camera2TextureView.java:411)
                                                                                at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.onCaptureProgressed(Camera2TextureView.java:379)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                                at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                                at android.os.Handler.handleCallback(Handler.java:754)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:163)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
06-21 10:45:08.924 25695-28453/com.eighteengray.procamera W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
06-21 10:45:08.925 25695-28453/com.eighteengray.procamera W/System.err:     at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.checkState(Camera2TextureView.java:411)
06-21 10:45:08.925 25695-28453/com.eighteengray.procamera W/System.err:     at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.onCaptureProgressed(Camera2TextureView.java:379)
06-21 10:45:08.926 25695-28453/com.eighteengray.procamera W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-21 10:45:08.926 25695-28453/com.eighteengray.procamera W/System.err:     at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
06-21 10:45:08.927 25695-28453/com.eighteengray.procamera W/System.err:     at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
06-21 10:45:08.929 25695-28453/com.eighteengray.procamera W/System.err:     at android.os.Handler.handleCallback(Handler.java:754)
06-21 10:45:08.930 25695-28453/com.eighteengray.procamera W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-21 10:45:08.930 25695-28453/com.eighteengray.procamera W/System.err:     at android.os.Looper.loop(Looper.java:163)
06-21 10:45:08.931 25695-28453/com.eighteengray.procamera W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
06-21 10:45:09.559 25695-26156/com.eighteengray.procamera W/art: Long monitor contention with owner main (25695) at void android.hardware.camera2.impl.CameraDeviceImpl.close()(CameraDeviceImpl.java:976) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 565ms
06-21 10:45:13.910 25695-28453/com.eighteengray.procamera I/Process: Sending signal. PID: 25695 SIG: 9`

**Comment by 18Gray** [comment]
加了个空指针保护，更新代码试一下
