### ISSUE TITLE
图片处理功能没法用

### ISSUE THREAD

**Issue by ithour** [18Gray/ProCamera#30]
图片处理功能没法用，看到你代码里面将相关按钮点击事件注释掉了，我重新开启后，会有空指针

**Comment by zjianflys** [comment]
你拍照的时候不会出现问题？

**Comment by zjianflys** [comment]
@ithour  对不对我没看 我是小米5s  连续拍照会卡死

- [ Process: com.eighteengray.procamera, PID: 14586
java.lang.IllegalStateException: maxImages (5) has already been acquired, call #close before acquiring more.
at android.media.ImageReader.acquireNextImage(ImageReader.java:398)
at com.eighteengray.procamera.business.ImageSaver.run(ImageSaver.java:39)
at java.lang.Thread.run(Thread.java:760)] 

报这个错  估计里面还有很多问题

**Comment by 18Gray** [comment]
图片处理功能暂时不要使用，这个功能我在整个重写，是按照SnapSeed那种滑动的方式在写，需要一些时间

**Comment by 18Gray** [comment]
拍照出错的问题，我查了api，官方文档给出的建议是把获取图像改用了另一个函数，不再推荐使用之前的函数。你们更新下代码，试试还有没有问题。
