### ISSUE TITLE
拍照多次相机会卡死

### ISSUE THREAD

**Issue by zjianflys** [18Gray/ProCamera#34]
- [ IllegalArgumentException while invoking public void android.hardware.camera2.CameraCaptureSession$CaptureCallback.onCaptureCompleted(android.hardware.camera2.CameraCaptureSession,android.hardware.camera2.CaptureRequest,android.hardware.camera2.TotalCaptureResult)
                                                                             java.lang.IllegalArgumentException: submitRequestList:221: Request targets Surface that is not part of current capture session
                                                                                 at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:651)
                                                                                 at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:86)
                                                                                 at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:935)
                                                                                 at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:824)
                                                                                 at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:181)
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView.doStillCapture(Camera2TextureView.java:405)
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView.access$300(Camera2TextureView.java:41)
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.checkState(Camera2TextureView.java:124)
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.onCaptureCompleted(Camera2TextureView.java:93)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                                 at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                                 at android.os.Handler.handleCallback(Handler.java:808)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                 at android.os.Looper.loop(Looper.java:166)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                              Caused by: android.os.ServiceSpecificException: submitRequestList:221: Request targets Surface that is not part of current capture session (code 3)
                                                                                 at android.os.Parcel.readException(Parcel.java:1959)
                                                                                 at android.os.Parcel.readException(Parcel.java:1891)
                                                                                 at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.submitRequestList(ICameraDeviceUser.java:334)
                                                                                 at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:84)
                                                                                 at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:935) 
                                                                                 at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:824) 
                                                                                 at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:181) 
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView.doStillCapture(Camera2TextureView.java:405) 
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView.access$300(Camera2TextureView.java:41) 
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.checkState(Camera2TextureView.java:124) 
                                                                                 at com.eighteengray.procameralibrary.camera.Camera2TextureView$3.onCaptureCompleted(Camera2TextureView.java:93) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39) 
                                                                                 at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:808) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:101) 
                                                                                 at android.os.Looper.loop(Looper.java:166) 
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:65) ]

**Comment by 18Gray** [comment]
我的小米Mix 2S目前也有这个状况，华为荣耀V9没有出现，目前正在排查。

**Comment by zjianflys** [comment]
恩,预览的时候 会有延时,你测试的机型有这种想象嘛？

**Comment by 18Gray** [comment]
我的小米NOTE 4X预览有卡顿，小米Mix 2S预览顺畅，直接拍照没问题，去相册返回再拍照出现上面这个bug。我的主要测试机型是华为荣耀V9，比较顺畅。
