### ISSUE TITLE
设置防手都就报错

### ISSUE THREAD

**Issue by 845479430** [18Gray/ProCamera#40]

**Comment by 18Gray** [comment]
加一下log吧，我这没有报错。

**Comment by 845479430** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
        at com.eighteengray.procameralibrary.camera.CaptureRequestFactory.createPreviewBuilder(CaptureRequestFactory.java:25)
        at com.eighteengray.procameralibrary.camera.Camera2TextureView.setSteadyPhoto(Camera2TextureView.java:226)
        at com.eighteengray.procamera.fragment.Camera2Fragment.onResume(Camera2Fragment.java:145)
@18Gray

**Comment by 18Gray** [comment]
代码提交了，你试下看有没有问题

**Comment by 845479430** [comment]
@18Gray 还是报错，同样问题。您用Fragment加载相机在低性能手机上会很卡，建议用activity
